# Generated by Django 3.2.5 on 2021-07-25 12:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sumo.common.mixins.validate_model_mixin


class Migration(migrations.Migration):

    dependencies = [
        ('basho', '0001_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torikumi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('basho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basho.basho')),
            ],
            options={
                'verbose_name_plural': 'Torikumi',
            },
            bases=(sumo.common.mixins.validate_model_mixin.ValidateModelMixin, models.Model),
        ),
    ]
