# Generated by Django 3.2.5 on 2021-07-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0002_add_basic_model_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rikishi',
            name='height',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='rikishi',
            name='weight',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
