# Generated by Django 3.2.5 on 2021-07-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0004_rikishi_shikona_and_heya_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rikishi',
            name='shikona_first',
            field=models.CharField(help_text="The rikishi's ring name.", max_length=255),
        ),
        migrations.AlterField(
            model_name='rikishi',
            name='shikona_second',
            field=models.CharField(help_text="The rikishi's ring name second name.", max_length=255),
        ),
    ]
