# Generated by Django 3.2.5 on 2021-07-16 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0005_rikishi_help_text_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rikishi',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(150), django.core.validators.MaxValueValidator(250)], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='rikishi',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(350)], verbose_name='Weight (kg)'),
        ),
        migrations.AddConstraint(
            model_name='heya',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name',), name='unique_name_for_active_heya'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('shikona_first',), name='unique_shikona_for_active_rikishi'),
        ),
    ]
