# Generated by Django 3.2.5 on 2021-07-12 20:09

from django.db import migrations, models
import django.db.models.deletion
import sumo.common.mixins.validate_model_mixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basho', '0001_setup'),
        ('rikishi', '0005_rikishi_help_text_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banzuke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='basho.basho')),
            ],
            options={
                'verbose_name_plural': 'Banzuke',
            },
            bases=(sumo.common.mixins.validate_model_mixin.ValidateModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BanzukeAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banzuke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banzuke.banzuke')),
                ('rikishi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rikishi.rikishi')),
            ],
        ),
        migrations.AddField(
            model_name='banzuke',
            name='competitors',
            field=models.ManyToManyField(through='banzuke.BanzukeAppearance', to='rikishi.Rikishi'),
        ),
    ]
