# Generated by Django 3.2.5 on 2021-07-16 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banzuke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banzukeappearance',
            name='division',
            field=models.IntegerField(choices=[(1, 'Makuuchi'), (2, 'Jūryō'), (3, 'Makushita'), (4, 'Sandanme'), (5, 'Jonidan'), (6, 'Jonokuchi')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banzukeappearance',
            name='makuuchi_rank',
            field=models.IntegerField(blank=True, choices=[(1, 'Yokozuna'), (2, 'Ōzeki'), (3, 'Sekiwake'), (4, 'Komusubi'), (5, 'Maegashira')], null=True),
        ),
        migrations.AddField(
            model_name='banzukeappearance',
            name='numeric_rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banzukeappearance',
            name='side',
            field=models.IntegerField(choices=[(1, 'East'), (2, 'West')], default=1),
            preserve_default=False,
        ),
    ]
