# Generated by Django 3.2.5 on 2021-07-15 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banzuke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banzukeappearance',
            name='division',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banzukeappearance',
            name='makuuchi_rank',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='banzukeappearance',
            name='numeric_rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
    ]
