# Generated by Django 3.2.5 on 2021-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banzuke', '0002_appearance_rank_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banzukeappearance',
            constraint=models.UniqueConstraint(fields=('banzuke', 'division', 'makuuchi_rank', 'numeric_rank', 'side'), name='unique_banzuke_rank'),
        ),
    ]
