# Generated by Django 3.2.5 on 2021-07-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rikishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=255)),
                ('name_second', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('birth_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
