# Generated by Django 3.2.5 on 2021-07-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0001_add_basic_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='rikishi',
            name='heya',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rikishi.heya'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rikishi',
            name='shusshin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rikishi.shusshin'),
            preserve_default=False,
        ),
    ]
