# Generated by Django 3.2.5 on 2021-07-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0001_add_rikishi_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
